name: Build V8
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-mac:
    name: mac
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: docker build
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
