name: Build V8
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-mac:
    name: mac
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: docker build
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          gclient
          mkdir $GITHUB_WORKSPACE/v8
          cd $GITHUB_WORKSPACE/v8
          echo "mac-arm64" > .cipd_client_platform
          export VPYTHON_BYPASS="manually managed python not supported by chrome operations"
          fetch v8
          git checkout branch-heads/11.8
          gclient sync
          mkdir -p out.gn/arm64.release/
          cp ../args.gn out.gn/arm64.release/args.gn
          gn gen out.gn/arm64.release
          ninja v8_monolith -C out.gn/arm64.release/
