name: test build
on: [push]

env:
  V8_VERSION: "13.1"

defaults:
  run:
    shell: bash

jobs:
  build-linux-x64:
#    if: ${{ false }}  # disable
    name: linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup v8 build tools
        run: |
          sudo apt-get update
          sudo apt-get install -yq ccache
          sudo update-ccache-symlinks
          echo "/usr/lib/ccache" >> "$GITHUB_PATH"
          ccacheDir="${GITHUB_WORKSPACE}/.ccache"
          test -d "$ccacheDir" || mkdir "$ccacheDir"
          echo "CCACHE_DIR=$ccacheDir" >> "$GITHUB_ENV"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          gclient
      - name: fetch beta branch
        run: |
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          fetch v8
          cd v8
          git checkout branch-heads/$V8_VERSION
          gclient sync
          mkdir -p out.gn/${{ matrix.platform }}.release/
      - name: build v8 static library
        run: |
          export PATH="$GITHUB_WORKSPACE/depot_tools:${PATH}"
          cp args.linux.${{ matrix.platform }}.gn $GITHUB_WORKSPACE/v8/out.gn/${{ matrix.platform }}.release/args.gn
          cd $GITHUB_WORKSPACE/v8
          gn gen out.gn/${{ matrix.platform }}.release
          ninja -j 4 v8_monolith -C out.gn/${{ matrix.platform }}.release/
          gn args --list out.gn/${{ matrix.platform }}.release
      - name: Compress static library
        run: |
          tar -zcvf out-${{ matrix.platform }}.tar.gz ${{ github.workspace }}/v8/out.gn/${{ matrix.platform }}.release
      - name: Upload static library
        uses: actions/upload-artifact@v4
        with:
          path: out-${{ matrix.platform }}.tar.gz
          name: out-${{ matrix.platform }}.tar.gz
