name: create release
on: 
  push:
    tags:
      - '[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:

  create-release:
#    if: ${{ false }}  # disable for now
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v8 Version ${{ github.ref_name }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md
